# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter_cocoapod_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios_project2' do
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end